### ISSUE TITLE
Query parameters for GET requests do not get passed to the official API

### ISSUE THREAD

**Issue by https123456789** [https123456789/GithubAPI#1]
# Query parameters for GET requests do not get passed to the official API

When a request is made, for example: `https://githubapi.https12345678.repl.co/github/users/https123456789/events?per_page=2`, the get parameters are not passed to the actual GitHub API request.

In the `retriveGithubAPIData` function:

[https://github.com/https123456789/GithubAPI/blob/c85a90fbb4d064141a67a17a2258870a1a555add/server/index.js#L55](https://github.com/https123456789/GithubAPI/blob/c85a90fbb4d064141a67a17a2258870a1a555add/server/index.js#L55)

the path variable passed, is used as the URL for the request. Unfortunately, the GET handler for `/github*` determines the path without factoring in the GET query.

[https://github.com/https123456789/GithubAPI/blob/c85a90fbb4d064141a67a17a2258870a1a555add/server/index.js#L80-L81](https://github.com/https123456789/GithubAPI/blob/c85a90fbb4d064141a67a17a2258870a1a555add/server/index.js#L80-L81)

This could be easily fixed by passing the GET query to the `retriveGithubAPIData` function.

**Comment by b0x207** [comment]
Fixed this with [0a0edfe9e0dfe2c339bd020caacc12cf3457dcc9](https://github.com/https123456789/GithubAPI/commit/0a0edfe9e0dfe2c339bd020caacc12cf3457dcc9).
